# Generated by Django 3.2.20 on 2023-09-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Customer', max_length=50),
        ),
    ]
