# Generated by Django 3.2.20 on 2023-09-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20230920_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='carbon_saved',
            new_name='carbon_saved_total',
        ),
    ]
