# Generated by Django 3.2.20 on 2023-08-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('wear', 'Wear'), ('care', 'Care'), ('eat', 'Eat'), ('travel', 'Travel')], max_length=254),
        ),
    ]
