# Generated by Django 3.2.20 on 2023-09-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230908_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_shoe',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
