# Generated by Django 3.2.20 on 2023-09-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ml_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
