# Generated by Django 3.2.20 on 2023-10-08 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_ml_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_shoe',
            new_name='shoe_sizes',
        ),
    ]
